#!/bin/bash
# Do one experiment
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=10G
#SBATCH --job-name=process_1
#SBATCH --output=process_1_%j.log
./familie_poen_solver $1 $2