#!/bin/bash
# Run all sims
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=exp_3
#SBATCH --output=process.log
sbatch ./process_1 CRR 1000000
sbatch ./process_1 HRR 1000000
sbatch ./process_1 LRR 1000000
sbatch ./process_1 RRR 1000000
sbatch ./process_1 URR 1000000
sbatch ./process_1 RCR 1000000
sbatch ./process_1 RHR 1000000
sbatch ./process_1 RLR 1000000
sbatch ./process_1 RRR 1000000
sbatch ./process_1 RUR 1000000
sbatch ./process_1 RRC 1000000
sbatch ./process_1 RRH 1000000
sbatch ./process_1 RRL 1000000
sbatch ./process_1 RRR 1000000
sbatch ./process_1 RRU 1000000
