#!/bin/bash
# Run all sims
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=exp_4
#SBATCH --output=exp_4.log
sbatch ./process_1 CRRR 1000000
sbatch ./process_1 HRRR 1000000
sbatch ./process_1 LRRR 1000000
sbatch ./process_1 RRRR 1000000
sbatch ./process_1 URRR 1000000
sbatch ./process_1 RCRR 1000000
sbatch ./process_1 RHRR 1000000
sbatch ./process_1 RLRR 1000000
sbatch ./process_1 RRRR 1000000
sbatch ./process_1 RURR 1000000
sbatch ./process_1 RRCR 1000000
sbatch ./process_1 RRHR 1000000
sbatch ./process_1 RRLR 1000000
sbatch ./process_1 RRRR 1000000
sbatch ./process_1 RRUR 1000000
sbatch ./process_1 RRRC 1000000
sbatch ./process_1 RRRH 1000000
sbatch ./process_1 RRRL 1000000
sbatch ./process_1 RRRR 1000000
sbatch ./process_1 RRRU 1000000
