#!/bin/bash
# Run all sims
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=exp_2
#SBATCH --output=process.log


for a in `echo "CHLRU" | grep -o .`
do
  for b in `echo "CHLRU" | grep -o .`
  do
    sbatch ./process_1 $a$b 10000
  done
done
