#!/bin/bash
# Run all sims
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=exp_3
#SBATCH --output=process.log
for a in `echo "CHLRU" | grep -o .`
do
  for b in `echo "CHLRU" | grep -o .`
  do
    for c in `echo "CHLRU" | grep -o .`
    do
      sbatch ./process_1 $a$b$c 1000000
    done
  done
done

