#!/bin/bash
# Run all sims
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=exp_2
#SBATCH --output=process.log
sbatch ./process_1 CR 1000000
sbatch ./process_1 HR 1000000
sbatch ./process_1 LR 1000000
sbatch ./process_1 RR 1000000
sbatch ./process_1 UR 1000000
sbatch ./process_1 RC 1000000
sbatch ./process_1 RH 1000000
sbatch ./process_1 RL 1000000
sbatch ./process_1 RR 1000000
sbatch ./process_1 RU 1000000
